print("Oi, tudo bem?")

print("que horas são?")
print("uma imagem de um cachorro")
print("0______")
print("  ||||  ")
print("eu tenho cinco cachorros")
print("moro em timon")
print("bom dia" * 8)
print("olá, " + "tudo bem?")
print("ha "*4)
print("ba" + "na"*2)
print("Bra" + "sil" + "!"*10)
print("#" *30)
print("#" *30)
print("#" *30)
print("/\ "*10)
print(" \/"*10)
print("<__* ")
print("---")
print("/")
print (".-^^^-")
print(".|_|-|_|")
print("/ /")
print(" --")
print(" ) ")
print("//")
print ("e aqui vai um bolo! hummmmmmmm")
print( "."*10)
print("i"*10)
print("#"*11)
print("="*11)
print("#"*11)
print("="*11)
