# -*- coding: utf-8 -*-
"""Sem-05-T1-Q05 Valor em loja de roupas.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qg6vLGuRWxVX2HCG7zBzEy01G-3uh4jl
"""

def valorPagoAVista(v):
    return v * 0.91

def valorPagoEmCincoVezes(v):
    return v/5

def valorPagoEmDezVezes(v):
    return (v * 1.17)/10

val_compra = float(input().strip())
print(f'{valorPagoAVista(val_compra):0.2f}')
print(f'{valorPagoEmCincoVezes(val_compra):0.2f}')
print(f'{valorPagoEmDezVezes(val_compra):0.2f}')