# -*- coding: utf-8 -*-
"""Sem-05-T1-Q01 Quantidade de caracteres de um nome.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_xonx3t_WeWxQCX5NBSM_RFBxRLVK-Rn
"""

def name():
  return len

if __name__ == "__main__":
  name = (input().strip())

print(len(name))

