# -*- coding: utf-8 -*-
"""Sem-05-T1-Q03 Duração de um evento.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lu0Ufm-8bV1HCmK4Y_dC0TUU34TSjx3q
"""

def evento():
  return segundos 
if __name__== "__main__":
  segundos = int(input())
  horas = (segundos//3600)
  minutos = ((segundos//60)%60)
  segundos = ((segundos%60)%60)%60
  print (f'{horas}HH:{minutos}:MM{segundos}:SS')

3