# -*- coding: utf-8 -*-
"""Sem-05-T1-Q02 Qual código de um caractere.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUs8J-P0WcJnSPa3zgWmynxq4ULcNBc0
"""

cod_caract = input()
print(ord(cod_caract))

