# -*- coding: utf-8 -*-
"""Sem-05-T1-Q04 Mínimo, máximo e média.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMyaS31LWLQ4NSzGj5PlVpDWyYCaphYe
"""

def numeros(a,b,c,d,e):
  return max
def numeros(a,b,c,d,e):
  return min
def numeros(a,b,c,d,e):
  return (a+b+c+d+e)/5
if __name__ == "__main__":
  a = int(input())
  b = int(input())
  c = int(input())
  d = int(input())
  e = int(input())
  media = (a+b+c+d+e)/5
print(max(a,b,c,d,e))
print(min(a,b,c,d,e))
print(media)

